"""Generate coach/coach_context.md — a compact training brief the LLM coach reads.

This is the rolling, data-derived half of the coach's knowledge. The athlete's
fixed goals/constraints live in coach/goal.md (hand-edited via /goal).
"""
from __future__ import annotations

from datetime import datetime
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
COACH = ROOT / "coach"


def _pace(sec):
    if sec is None or not (sec == sec):  # NaN guard
        return "—"
    m, s = divmod(int(round(sec)), 60)
    return f"{m}:{s:02d}/mi"


def write_coach_context(runs: pd.DataFrame, summary: dict) -> None:
    COACH.mkdir(parents=True, exist_ok=True)
    now = datetime.now().strftime("%Y-%m-%d")
    t = summary["totals"]

    # Last 8 ISO weeks of mileage.
    weekly = pd.DataFrame(summary["weekly"])
    weekly["week"] = pd.to_datetime(weekly["x"])
    recent_weeks = weekly.tail(8)

    # Recent runs (last 14).
    recent = runs.sort_values("date").tail(14)

    # Best efforts (running PRs) from the per-run efforts already computed.
    pr = {}
    for label, entries in summary["pr_progression"].items():
        prs = [e for e in entries if e["is_pr"]]
        if prs:
            pr[label] = prs[-1]

    fitness = summary["fitness"][-1] if summary["fitness"] else {}

    lines = []
    lines.append("# Coach Context (auto-generated)")
    lines.append(f"_Generated {now} from {t['runs']} runs "
                 f"({t['first']} → {t['last']}). Do not edit by hand — regenerated by the pipeline._")
    lines.append("")
    lines.append("## Career totals")
    lines.append(f"- {t['miles']:.0f} mi over {t['hours']:.0f} h, {t['elev_ft']:.0f} ft climbed "
                 f"({t['elev_everest']}× Everest).")
    lines.append("")
    lines.append("## Current fitness (training-load model)")
    if fitness:
        lines.append(f"- Fitness (CTL, 42d): **{fitness['ctl']}**  ·  "
                     f"Fatigue (ATL, 7d): **{fitness['atl']}**  ·  "
                     f"Form (TSB): **{fitness['tsb']}**")
        tsb = fitness["tsb"]
        note = ("fresh/tapered" if tsb > 5 else "balanced" if tsb > -10
                else "carrying fatigue" if tsb > -25 else "deep in a load block — watch recovery")
        lines.append(f"- Form reads as: _{note}_.")
    lines.append("")
    lines.append("## Last 8 weeks of volume")
    lines.append("| Week of | Miles | Runs | Elev (ft) |")
    lines.append("|---|---|---|---|")
    for _, w in recent_weeks.iterrows():
        lines.append(f"| {w['x']} | {w['miles']:.1f} | {int(w['runs'])} | {w['elev_ft']:.0f} |")
    lines.append("")
    lines.append("## Running best efforts (fastest segment within any run)")
    for label in ["1 mi", "5k", "10k", "Half", "Marathon"]:
        if label in pr:
            lines.append(f"- **{label}**: {pr[label]['time']} (on {pr[label]['date']})")
    lines.append("")
    lines.append("## Last 14 runs")
    lines.append("| Date | Name | Type | Miles | Pace | GAP | Avg HR | Effort |")
    lines.append("|---|---|---|---|---|---|---|---|")
    for _, r in recent.iterrows():
        hr = f"{r['avg_hr']:.0f}" if pd.notna(r["avg_hr"]) else "—"
        eff = f"{r['rel_effort']:.0f}" if pd.notna(r["rel_effort"]) else "—"
        desc = f" — {r['description'][:40]}" if r["description"] else ""
        lines.append(
            f"| {r['date'].strftime('%Y-%m-%d')} | {r['name'][:24]}{desc} | {r['type']} | "
            f"{r['distance_mi']:.1f} | {_pace(r['pace_s'])} | {_pace(r['gap_pace_s'])} | "
            f"{hr} | {eff} |"
        )
    lines.append("")
    lines.append("## Easy/hard balance")
    eh = summary["easy_hard_split"]
    lines.append(f"- Easy/long runs: {eh['easy']}  ·  Workouts/races: {eh['hard']} "
                 f"(over full history).")
    lines.append("")

    (COACH / "coach_context.md").write_text("\n".join(lines))
